service: hgc-frontend-tests-infra

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: af-south-1
  stage: ${opt:stage, 'dev'}
  profile: mweb
  timeout: 30
  memorySize: 256
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    S3_BUCKET: !Ref TestResultsBucket
    DYNAMODB_TABLE: !Ref TestRunsTable
    GITHUB_TOKEN: ${ssm:/hgc-frontend-tests/${self:provider.stage}/github-token}
  apiGateway:
    shouldStartNameWithService: true
    apiKeys:
      - ${self:service}_${self:provider.stage}
    binaryMediaTypes:
      - '*/*'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - "arn:aws:s3:::hgc-test-results-${self:provider.stage}"
            - "arn:aws:s3:::hgc-test-results-${self:provider.stage}/*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt TestRunsTable.Arn
            - !Sub "${TestRunsTable.Arn}/index/*"
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource:
            - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/hgc-frontend-tests/${self:provider.stage}/*"

functions:
  api:
    handler: src.handler.handler
    timeout: 29 # max number of seconds for API GW
    events:
      - http: 
          method: ANY
          path: /{proxy+}
          private: true

resources:
  Resources:
    TestResultsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hgc-test-results-${self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        LifecycleConfiguration:
          Rules:
            - Id: DeleteAfter90Days
              Status: Enabled
              ExpirationInDays: 90
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000

    TestRunsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hgc-test-runs-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: gsi1pk
                KeyType: HASH
              - AttributeName: gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    ApiKeyParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /hgc-frontend-tests/${self:provider.stage}/api-key
        Description: API key for HGC frontend test automation
        Type: String
        Value: !Ref ApiGatewayApiKey1

  Outputs:
    S3BucketName:
      Description: S3 Bucket for test results
      Value: !Ref TestResultsBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-s3-bucket
    
    DynamoDBTableName:
      Description: DynamoDB table for test runs
      Value: !Ref TestRunsTable
      Export:
        Name: ${self:service}-${self:provider.stage}-dynamodb-table
    
    ApiKeyId:
      Description: API Gateway API Key ID
      Value: !Ref ApiGatewayApiKey1
      Export:
        Name: ${self:service}-${self:provider.stage}-api-key-id

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false